name: "Memorable milestones"
on:
  schedule:
  - cron: 0/20 * * * *

jobs:
  memorable-milestones:
    runs-on: ubuntu-latest
    steps:
    - name: Memorable milestones message
      run: echo Checking for milestones to create or close
    - uses: actions/checkout@v2
    - uses: ./
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
